/* generated by tools/png_to_rgb565.py from plain.320.png (dither: bayer) — do not edit */
#ifndef FAM_PLATE_PLAIN_H
#define FAM_PLATE_PLAIN_H
#include <stdint.h>
#define PLATE_PLAIN_W 320
#define PLATE_PLAIN_H 170
extern const uint16_t plate_plain[320 * 170];
#endif
