#!/usr/bin/env python3
"""
Bake Bitcount Grid Single into the same C tables generate_fonts.py produces,
so baked_font.c / menu.c / oled_draw.c keep working unchanged.

  python3 tools/generate_fonts_bitcount.py \
      <regular.ttf> <semibold.ttf> src/baked_font_data.c

WHY A SEPARATE BAKER

Bitcount is a grid font, not a contour font that happens to be blocky. Its
glyphs are dots on a 0.1 em lattice (advance 600/1000 units = 6 modules, and
the face is monospaced). Two consequences drive everything here:

  1. ppem MUST be a multiple of 10. Then one grid module is exactly ppem/10
     pixels and every dot lands on whole pixels. At 8, 9 or 16 px a module
     falls on 0.8 / 0.9 / 1.6 pixels, every dot gets interpolated across pixel
     boundaries, and the text turns to mush. The assert below enforces this.

  2. Render MONOCHROME, not anti-aliased. AA is what makes a normal typeface
     look smooth, and it is exactly what destroys a grid font — it smears the
     lattice. Coverage here is binary: 0 or 15 in the 4-bit framebuffer.

LICENSING: Bitcount is SIL Open Font License 1.1, so unlike the Helvetica Neue
faces the previous baker consumed, the source TTFs can live in the repo and
ship in a product. OFL.txt must travel with any redistribution.
"""
import sys

try:
    import freetype
except ImportError:
    sys.exit("needs freetype-py:  pip install freetype-py")

CHARSET = [chr(c) for c in range(32, 127)]      # printable ASCII

# name, ttf slot, ppem. Multiples of 10 only — see the module note above.
# Roles mirror generate_fonts.py so nothing downstream has to change.
#
# Size also picks the LOOK, which is specific to this face: the dots are one
# module across and sit one module apart, so at module 1-2 px they merge into
# solid strokes, and from module 3 px up the lattice becomes visible as
# separate dots. The reference design uses solid strokes, hence the small
# modules here. Go to 40/60 if the dotted look is wanted for the big value.
FACES = [
    ("font_hn_value",       1, 30),   # big value  — module 3 px, lattice just visible
    ("font_hn_value_small", 1, 20),   # long-word fallback — module 2 px, solid
    ("font_hn_label",       0, 10),   # labels / secondary — module 1 px, solid
]


def bake(path, ppem):
    if ppem % 10:
        sys.exit(f"ppem {ppem} is not a multiple of 10 — Bitcount's grid module "
                 f"is 0.1 em, so a non-multiple renders off-grid and illegible.")
    face = freetype.Face(path)
    face.set_pixel_sizes(0, ppem)
    ascent = face.size.ascender >> 6
    line   = face.size.height   >> 6
    glyphs, nibbles = [], []
    for ch in CHARSET:
        face.load_char(ch, freetype.FT_LOAD_RENDER
                           | freetype.FT_LOAD_TARGET_MONO
                           | freetype.FT_LOAD_MONOCHROME)
        g, bm = face.glyph, face.glyph.bitmap
        w, h = bm.width, bm.rows
        off = len(nibbles)
        for r in range(h):
            for c in range(w):
                bit = (bm.buffer[r * bm.pitch + (c >> 3)] >> (7 - (c & 7))) & 1
                nibbles.append(15 if bit else 0)     # binary coverage, no AA
        glyphs.append((g.advance.x >> 6, g.bitmap_left, g.bitmap_top, w, h, off))
    data = bytearray()
    for i in range(0, len(nibbles), 2):
        hi = nibbles[i]
        lo = nibbles[i + 1] if i + 1 < len(nibbles) else 0
        data.append((hi << 4) | lo)
    return ascent, line, glyphs, data


def emit(f, name, ascent, line, glyphs, data):
    f.write(f"\n/* ---- {name} ---- */\n")
    f.write(f"static const uint8_t {name}_data[] = {{\n")
    for i in range(0, len(data), 20):
        f.write("  " + ",".join(str(b) for b in data[i:i + 20]) + ",\n")
    f.write("};\n")
    f.write(f"static const bglyph_t {name}_glyphs[{len(glyphs)}] = {{\n")
    for adv, left, top, w, h, off in glyphs:
        f.write(f"  {{{adv},{left},{top},{w},{h},{off}}},\n")
    f.write("};\n")
    f.write(f"const bakedfont_t {name} = {{ {ascent},{line},32,{len(glyphs)}, "
            f"{name}_glyphs, {name}_data }};\n")


def main() -> int:
    if len(sys.argv) != 4:
        sys.exit(__doc__)
    regular, semibold, out = sys.argv[1:4]
    srcs = [regular, semibold]

    with open(out, "w") as f:
        f.write("/* GENERATED by tools/generate_fonts_bitcount.py — do not edit by hand.\n"
                " * Bitcount Grid Single baked MONOCHROME on its native 0.1 em grid.\n"
                " * Coverage is binary (0 or 15): anti-aliasing would smear the lattice\n"
                " * and is what made earlier off-grid renders illegible. */\n"
                '#include "baked_font.h"\n')
        total = 0
        for name, slot, ppem in FACES:
            ascent, line, glyphs, data = bake(srcs[slot], ppem)
            emit(f, name, ascent, line, glyphs, data)
            total += len(data)
            mod = ppem // 10
            print(f"{name:<22} ppem {ppem:3d}  module {mod} px  "
                  f"advance {ppem * 6 // 10:2d} px  ascent {ascent:2d}  "
                  f"{len(data):6d} byte")
    print(f"{'total glyph data':<22} {total:6d} byte -> {out}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
