#!/usr/bin/env python3
"""
Bake Helvetica Neue OTF glyphs into C tables at exact pixel sizes.

Per ChatGPT's pipeline: render at native resolution, anti-aliased, quantise to
the SSD1322's 4-bit grey, NO runtime scaling. The Pico blits these baked AA
bitmaps 1:1. Light for the big value, Thin for the small labels.

Run from firmware-c-next/ (OTFs are user-supplied, NOT in the repo):
  python3 tools/generate_fonts.py <light.otf> <thin.otf> src/baked_font_data.c

LICENSING: Helvetica Neue is a commercial font. The OTF files are git-ignored;
the baked glyph subset is committed so the firmware builds, but a SHIPPING
product needs a proper Helvetica licence or a libre substitute (e.g. Inter,
Archivo, or a custom face) re-baked through this same tool.
"""
import sys, freetype

CHARSET = [chr(c) for c in range(32, 127)]   # printable ASCII

def bake(path, px):
    face = freetype.Face(path)
    face.set_pixel_sizes(0, px)
    ascent = face.size.ascender >> 6
    line   = face.size.height   >> 6
    glyphs = []
    allnibs = []                       # ONE continuous nibble stream per font
    for ch in CHARSET:
        face.load_char(ch, freetype.FT_LOAD_RENDER | freetype.FT_LOAD_TARGET_NORMAL)
        g = face.glyph; bm = g.bitmap
        w, h, pitch = bm.width, bm.rows, bm.pitch
        adv  = (g.advance.x + 32) >> 6
        left = g.bitmap_left
        top  = g.bitmap_top
        off  = len(allnibs)            # nibble offset = current stream length
        for r in range(h):
            for c in range(w):
                v8 = bm.buffer[r * pitch + c]
                allnibs.append((v8 * 15 + 127) // 255)
        glyphs.append((adv, left, top, w, h, off))
    # pack the whole stream once (2 nibbles/byte), pad final byte if needed
    data = bytearray()
    for i in range(0, len(allnibs), 2):
        hi = allnibs[i]
        lo = allnibs[i + 1] if i + 1 < len(allnibs) else 0
        data.append((hi << 4) | lo)
    return ascent, line, glyphs, bytes(data)

def emit(out, name, ascent, line, glyphs, data):
    out.write(f"\n/* ---- {name} ---- */\n")
    out.write(f"static const uint8_t {name}_data[] = {{\n")
    for i in range(0, len(data), 20):
        out.write("  " + ",".join(str(b) for b in data[i:i+20]) + ",\n")
    out.write("};\n")
    out.write(f"static const bglyph_t {name}_glyphs[{len(glyphs)}] = {{\n")
    for (adv, left, top, w, h, off) in glyphs:
        out.write(f"  {{{adv},{left},{top},{w},{h},{off}}},\n")
    out.write("};\n")
    out.write(f"const bakedfont_t {name} = {{ {ascent},{line},32,{len(glyphs)}, "
              f"{name}_glyphs, {name}_data }};\n")

def main():
    light, thin, outpath = sys.argv[1], sys.argv[2], sys.argv[3]
    fonts = [
        ("font_hn_value",       light, 32),   # big value (primary)
        ("font_hn_value_small", light, 20),   # big value fallback (long words)
        ("font_hn_label",       thin,  13),   # labels / secondary
    ]
    with open(outpath, "w") as out:
        out.write("/* GENERATED by tools/generate_fonts.py — do not edit by hand.\n"
                  " * Helvetica Neue Light/Thin baked to 4-bit AA glyph bitmaps. */\n")
        out.write('#include "baked_font.h"\n')
        for (name, path, px) in fonts:
            a, l, g, d = bake(path, px)
            emit(out, name, a, l, g, d)
            sys.stderr.write(f"{name}: ascent={a} line={l} glyphs={len(g)} data={len(d)}B\n")
    sys.stderr.write(f"wrote {outpath}\n")

if __name__ == "__main__":
    main()
